# Main Snakefile and entry point of the workflow.
# Please see the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

# set config file where you can specify your inputs
configfile: "config/config.yaml"

# set {samples} global variable - used to read Hi-C files
samples_in_pattern = "{sample}_1.fastq.gz"
samples = glob_wildcards(config["hic_path"] + samples_in_pattern).sample

# set {diploid_mode} global variable - used to run hifiasm_het rather than hifiasm
diploid_mode=config["hifiasm"]["optional_params"]["--h1"] and config["hifiasm"]["optional_params"]["--h2"]

# Include the common rule, where the inputs for rule_all are defined
include: "rules/common.smk"
# Include the hifi_prep rule
include: "rules/hifi_prep.smk"
# Include the nanoplot
include: "rules/nanoplot.smk"
# Include the kmc rule
include: "rules/kmc.smk"
# Include the genomescope2 rule
include: "rules/genomescope2.smk"
# Include the oatk rule
include: "rules/oatk.smk"
# Include the hifiasm rule
include: "rules/hifiasm.smk"
# Include the ncbi_fcsgx rule
include: "rules/ncbi_fcsgx.smk"  # to add if eventually I manage to integrate fcsgx
# Include the purge_dups rule
include: "rules/purge_dups.smk"
# Include the purge_dups2 rule for alternate assembly
include: "rules/purge_dups2.smk"
# Include the fastp rule
include: "rules/fastp.smk"
# Include the bwa_index rule
include: "rules/bwa_index.smk"
# Include the bwa_mem rule
include: "rules/bwa_mem.smk"
# Include the filter_five_end rule
include: "rules/filter_five_end.smk"
# Include the two_read_bam_combiner rule
include: "rules/two_read_bam_combiner.smk"
# Include the picard rule
include: "rules/picard.smk"
# Include the yahs rule
include: "rules/yahs.smk"


# Define the rule all, which is the default rule that Snakemake runs when no specific rule or target is specified
# input files are defined in the common.smk file
rule all:
    input:
        get_all_inputs
