# This rule run genomescope2 to allow the inspection of kmers profile. Kmers are first generated by KMC


rule genomescope2:
    input:
        "results/kmc/out.hist",
    output:
        directory("results/genomescope"),
    params:
        k=config["kmc"]["k"],
        optional_params=" ".join(
            f"{k} {v}" for k, v in config["genomescope2"]["optional_params"].items() if v
        ),
    log:
        "logs/genomescope2.log",
    resources:
        mem_mb=config["medium"]["mem_mb"],  # access memory from config    
    conda:
        "../envs/genomescope2.yaml"
    shell:
        """
        genomescope2 -i {input} -o {output} -k {params.k} {params.optional_params} >> {log} 2>&1
        """
