# This rule run genomescope2 to allow the inspection of kmers profile. Kmers are first generated by KMC

rule run_genomescope2:
    input:
        "results/kmc/out.hist"
    output:
        directory("results/genomescope")
    log:
        "logs/genomescope2.log"
    conda:
        "../envs/genomescope2.yaml"
    shell:
        """
        genomescope2 -i {input} -o {output} -k {config[kmc][k]} >> {log} 2>&1
        """