# config.yaml

# Path to hifi reads
hifi_path: "resources/raw_hifi/"

# Path to hic reads
hic_path: "resources/raw_hic/"

# Customisable parameters for nanoplot
nanoplot:
  t: 20 # number of threads

# Customisable parameters for fastp 
fastp:
  t: 20 # number of threads
  cut_window_size: 4
  cut_mean_quality: 20
  optional_params: 
    "--detect_adapter_for_pe": "true"
    "--cut_front": "true"
    "--cut_tail": "true"
    "-p": "false"

# Customisable parameters for kmc
kmc:
  k: 21 # kmer size, it will be the same used for genomescope2
  t: 20 # number of threads
  ci: 1 # exclude k-mers occurring less than <value> times (default: 2)
  cs: 100000 #maximal value of a counter (default: 255)

# Customisable parameters for kmc_tools transform
kmc_tools:
  cx: 100000 # exclude k-mers occurring more of than <value> times

# Customisable parameters for oatk
oatk:
  k: 1001 # kmer size [1001]
  c: 150 #  minimum kmer coverage [3]
  t: 20  # number of threads [1]
  m: "resources/oatkDB/path/to/mito/db_mito.fam" # mitochondria gene annotation HMM profile database [NULL]
  optional_params: 
    "-p": "" # resources/oatkDB/path/to/plastid/db_pltd.fam - to use for species that have a plastid db, leave empty if not available

# Customisable parameters for minimap2
minimap2:
  t: 20  # number of threads

# Customisable parameters for hifiasm
hifiasm:
  t: 50  # number of threads
  optional_params: 
    "-f": "0" # used for small datasets
    "-l": "" # purge level. 0: no purging; 1: light; 2/3: aggressive [0 for trio; 3 for unzip]

# Set this to False if you want to skip purge_dups steps:
include_purge_dups: False

# Customisable parameters for arima mapping pipeline:
arima:
  MAPQ_FILTER: 10
  CPU: 12

# Customisable parameters for yahs
yahs:
  o: "hifiasm_p_purged_yahs" # output prefix
  optional_params: 
    "-e": "GATC" # you can specify the restriction enzyme(s) used by the Hi-C experiment